Oracle index
securesecrets/shade pull request #143
Opened 2021-12-09 23:24 UTC by DrPresident

Initial testing looks good, I can test more thoroughly once we have BAND on pulsar-1. Currently uses a basic weighted average,  this is the basic test case I used:

price | weight
1.00  | .5
7.5    | .5
(1.0 * .5) + (7.5 * .5) = 4.25

This still needs testing with sswap pairs and such, but using band it is working well

2021-12-13 00:49 UTC, FloppyDisck requested changes

2021-12-13 00:49 UTC, FloppyDisck commented on contracts/oracle/README.md
> +|admin     | string   |  New contract owner; SHOULD be a valid bech32 address, but contracts may use a different naming scheme as well    |  yes     |
```suggestion
|admin     | string   |  New contract admin; SHOULD be a valid bech32 address, but contracts may use a different naming scheme as well    |  yes     |
```

2021-12-13 00:49 UTC, FloppyDisck commented on test-index.py
> +#!/usr/bin/env python3
Since the indexes are self contained equations, could you make unit tests in addition to these integration tests?

2021-12-13 20:26 UTC, DrPresident commented on test-index.py
> +#!/usr/bin/env python3
Basically all the functions require queries to either band or secretswap

2021-12-14 23:21 UTC, FloppyDisck commented on test-index.py
> +#!/usr/bin/env python3
Could those functions be moved into individual functions so you can spoof that data?

2021-12-14 23:21 UTC, FloppyDisck approved these changes

2021-12-14 23:32 UTC, merged