[governance] query proposal by status
securesecrets/shade pull request #144
Opened 2021-12-14 19:50 UTC by LasTshaMAN

Closes https://github.com/securesecrets/shade/issues/136

Hello guys, recently I've started looking into Rust and thought I'd check out Shade protocol code,
decided to try to implement this feature (seemed like a "good first issue"), so here it is,
if you've got some time for this, any feedback would be welcome :)

Side-note: maybe I should refactor my unit-tests a bit to get rid of duplicated code ?

2021-12-14 23:38 UTC, FloppyDisck commented on contracts/governance/src/query.rs
> +use shade_protocol::governance::Vote::No;
```suggestion
use shade_protocol::governance::{QueryAnswer, QueriedProposal, ProposalStatus, Vote::No};
```

2021-12-14 23:38 UTC, FloppyDisck commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
Because of the addition of status the current way of querying will always return less than the expected amount if status is Some.

I suggest using a while loop and listening for when the proposal's length is either max or total

2021-12-14 23:38 UTC, FloppyDisck commented on contracts/governance/Cargo.toml
> +serde_json = { version = "1.0.67"}
Is this import used?

2021-12-14 23:38 UTC, FloppyDisck commented on contracts/governance/src/test.rs
> +#[cfg(test)]
We're currently not using these unit tests as they're very cluttered. I would love to teach you about the custom framework we're using.

2021-12-14 23:42 UTC, DrPresident reviewed
Thanks for the help on this! it looks good just a couple suggestions. Also you should ping @mohammedpatla on telegram.

2021-12-14 23:42 UTC, DrPresident commented on contracts/governance/src/query.rs
> +        proposals.push(proposal)
this might be better like 
```
if let Some(s) = &status {
    if s != &proposal.status {
        continue
    }
}
proposals.push(proposal)
```

2021-12-14 23:42 UTC, DrPresident commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
For this function, could you break these individual tests into their own functions? You could try to parameterize them e.g. https://github.com/securesecrets/shade/blob/main/contracts/oracle/src/test.rs

2021-12-14 23:42 UTC, DrPresident commented on contracts/governance/Cargo.toml
> +serde_json = { version = "1.0.67"}
Is this used?

2021-12-15 08:26 UTC, LasTshaMAN commented on contracts/governance/Cargo.toml
> +serde_json = { version = "1.0.67"}
I'm using it in tests here: https://github.com/securesecrets/shade/pull/144/files#diff-774e1282b450306a1e542cc06f593d6d9f995d6753be1d540c10f2de06b4266fR53

similar to how it is used in `testnet_integration.rs` (used it as example for these unit-tests)

2021-12-15 08:27 UTC, LasTshaMAN commented on contracts/governance/Cargo.toml
> +serde_json = { version = "1.0.67"}
I'm using it in tests here: https://github.com/securesecrets/shade/pull/144/files#diff-774e1282b450306a1e542cc06f593d6d9f995d6753be1d540c10f2de06b4266fR53

similar to how it is used in `testnet_integration.rs` (used it as example for these unit-tests)

2021-12-15 08:29 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
> +use shade_protocol::governance::Vote::No;
I'm wondering whether Rust has any code-formatting tools (similar to `goimports` maybe) ?

2021-12-15 08:32 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
I'm not sure what you mean by "will always return less than the expected amount if status is Some.",

can you elaborate on it ? (I think we can add a test case for this as well),

Does this https://github.com/securesecrets/shade/pull/144#discussion_r769129225 solve that issue ?

2021-12-15 08:43 UTC, LasTshaMAN commented on contracts/governance/src/test.rs
> +#[cfg(test)]
I've tried to spin up `testnet_integration.rs` but it seems smart contract needs to be compiled into wasm representation first, and I couldn't quite figure it out (based on what docs I found),

do I need to have "special Trusted Hardware" to spin up a working devnet/testnet ?

If you have any docs on this I'd love to learn more :) my Telegram handle should be `iur_ii`, feel free to ping me there (if that's convenient for you)

2021-12-15 08:43 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
> +        proposals.push(proposal)
That definitely looks better :) will apply

2021-12-15 08:50 UTC, LasTshaMAN commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
it depends on what's our goal with these tests is,

I've wrote these to "be specific to the feature I'm implementing", not intending to cover whole "GetProposal" functionlaity,
so, convering a couple of check into parametrized test could be an overkill IMO (they seem to be a bit harder to read/write),

but if we want to test "GetProposal" against different inputs (not just "status feature" which this PR is about), then parametrizing probably will be better solution, so I you want me to I can try

2021-12-15 08:53 UTC, LasTshaMAN commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
@FloppyDisck is mentioning some testing framework here https://github.com/securesecrets/shade/pull/144#discussion_r769128679

maybe we should decide on testing strategy first before proceeding with this ?

2021-12-15 11:53 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
> +use shade_protocol::governance::Vote::No;
I guess that's what I'm looking for - https://github.com/intellij-rust/intellij-rust/issues/2158

and maybe `cargo check` / `cargo fix` could help as well ... just wondering what you guys are using ?

2021-12-15 22:40 UTC, DrPresident commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
Agreed, Ideally I think both would be beneficial as these would be "unit tests" vs "integration tests", but I'm also not totally spun up on the other rust tests. I think these tests are good, I would like to see it simplified into a base function with parametrization but I'm also not fond of being too nit-picky about the tests and I think this works fine as-is.

2021-12-16 06:05 UTC, FloppyDisck commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
Lets say theres 100 proposals, my start is 1 and I want a total of 50 values where the ProposalStatus is Accepted. If in the next 50 values theres 5 that are InProgress; then the query will return 45 values instead.

2021-12-16 06:08 UTC, FloppyDisck commented on contracts/governance/Cargo.toml
> +serde_json = { version = "1.0.67"}
You could move it under dev-dependencies since its only used for testing

```suggestion
[dev-dependencies]

serde_json = { version = "1.0.67"}
```

2021-12-16 06:26 UTC, FloppyDisck commented on contracts/governance/src/test.rs
> +#[cfg(test)]
This is my bad, I failed to provide any good documentation for it.

In the root folder you can ```make``` and that will build all of the contracts. Then just write ```cargo test -- --nocapture --test-threads=1``` and that should be fine.

2021-12-16 06:28 UTC, FloppyDisck commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
I agree with @DrPresident its good to have a balance between both. I usually tend to write them as integration tests when testing the whole contract and use unit tests for individual functions.

2021-12-16 09:51 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
right, got it,

I guess I was treating `start` and `total` as pagination params, 
meaning the entity requesting proposals can send second request to  grind through proposals 51..100 (possibly getting less than 50 in the result as well),

if it is implemented as you describe, doesn't it kinda break pagination (resulting in duplicates when paginating via `start` and `total`) ?

suppose I want to find **all** proposals in Accepted status, and I have a history of 10 000 proposals (some are in Accepted, others are not),
I can iterate over these in 10 000 / 50 requests each time fetching a bunch (of lenght between 0 and 50) of proposals in Accepted status,
does the implementation you describe support such use-case ? (does it need to ?)

2021-12-16 12:04 UTC, LasTshaMAN commented on contracts/governance/src/test.rs
> +    fn get_proposals_by_status() {
I've moved some duplicated code into separate `assert_fn`.

2021-12-16 12:20 UTC, LasTshaMAN commented
Squashed all commits into one.

2021-12-16 14:57 UTC, FloppyDisck commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
Good point, I guess it would be best to rename total to something like end to be easier to understand.

2021-12-16 15:02 UTC, FloppyDisck requested changes
Everything seems great to me, all that's missing is resolving this comment https://github.com/securesecrets/shade/pull/144/files#r770615444

2021-12-16 15:53 UTC, LasTshaMAN commented on contracts/governance/src/query.rs
>      for i in clamped_start.u128()..((total+clamped_start).min(max).u128() + 1) {
Renamed to `end`, and changed the order of parameters this function (and other similar entities) accepts (so that it reads well).

2021-12-18 23:41 UTC, FloppyDisck approved these changes

2021-12-19 20:03 UTC, merged