Treasury allowance
securesecrets/shade pull request #173
Opened 2022-01-27 22:52 UTC by DrPresident

Added monthly allowance to an assets list of allocations. This amount can be refreshed 1x a month, meaning you could refresh on the Jan 30th, then again on Feb 1st. It will query your existing allowance and increase to the monthly amount if it is below, or decrease it to the monthly amount if it is above. Refreshing will refresh all allowances on all assets.

2022-02-01 14:48 UTC, FloppyDisck requested changes

2022-02-01 14:48 UTC, FloppyDisck commented on contracts/treasury/src/contract.rs
> +    let timestamp = "0".parse::<i64>().unwrap();
why not just write 
```suggestion
    let timestamp = 0;
```

2022-02-01 14:48 UTC, FloppyDisck commented on contracts/treasury/src/contract.rs
>      viewing_key_w(&mut deps.storage).save(&msg.viewing_key)?;
you could also read into implementing rng so we never have access to the viewing key 
https://scrt.network/blog/secret-feature-secret-oracles

2022-02-01 14:48 UTC, FloppyDisck commented on contracts/treasury/src/state.rs
> +pub static ASSET_LIST: &[u8] = b"asset_list";
can you add the `KEY` suffix to avoid any possible confusion?

2022-02-01 14:48 UTC, FloppyDisck commented on makefile
> +(cd $(contracts_dir)/$(1); RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked --features="debug-print")
this build is generally slower than building the whole project once, this is why its called `compress` and called after `build_release` or `build_debug`

2022-02-01 15:10 UTC, DrPresident commented on contracts/treasury/src/state.rs
> +pub static ASSET_LIST: &[u8] = b"asset_list";
what confusion? these variables arent used anywhere outside this file

2022-02-01 15:11 UTC, DrPresident commented on makefile
> +(cd $(contracts_dir)/$(1); RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked --features="debug-print")
The makefile as you had changed it wouldn't rebuild the contract on a `make treasury`, I had to rebuild the entire thing to get  my changes into the build.

2022-02-01 15:22 UTC, DrPresident commented on contracts/treasury/src/contract.rs
>      viewing_key_w(&mut deps.storage).save(&msg.viewing_key)?;
All of the balances are public so it doesn't really matter what the viewing key is

2022-02-01 18:34 UTC, FloppyDisck commented on contracts/treasury/src/contract.rs
>      viewing_key_w(&mut deps.storage).save(&msg.viewing_key)?;
will treasury be receiving any funds from non shade smart contracts? Cause the viewing key also allows you to check tx history

2022-02-01 18:35 UTC, FloppyDisck commented on contracts/treasury/src/state.rs
> +pub static ASSET_LIST: &[u8] = b"asset_list";
theyre still public, actually why do we even keep our smart contracts keys public, i think we can set them to private in a later PR

2022-02-01 18:39 UTC, FloppyDisck requested changes

2022-02-01 18:39 UTC, FloppyDisck commented on makefile
> +(cd $(contracts_dir)/$(1); RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked --features="debug-print")
Why not use `make` instead? Any contract that has already been built will be skipped. Or generalize the `compress_wasm` and `build_release` to use one contract instead of many

2022-02-01 18:54 UTC, DrPresident commented on makefile
> +(cd $(contracts_dir)/$(1); RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked --features="debug-print")
bc make rebuilds everything, it takes way more time and all I need to do is `make treasury`. Without these changes `make treasury` does basically nothing except re-run unit-tests on whatever build is already there, which doesn't make sense

2022-02-01 18:56 UTC, DrPresident commented on contracts/treasury/src/contract.rs
>      viewing_key_w(&mut deps.storage).save(&msg.viewing_key)?;
It definitely has the potential to receive from many different smart contracts, as well as any configured snip-20. If we need the viewing key to be more secure we can set it to something more complex at init. It could generate something itself but thats not really relevant to this PR and something that could be added later.

2022-02-02 18:36 UTC, FloppyDisck commented on makefile
> +(cd $(contracts_dir)/$(1); RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown --locked --features="debug-print")
Could you atleast fix it so it doesnt take longer when runningmake? For example, removing --features="debug-print" and preventing it from compiling individual contracts after build_release or build_debug is called.

2022-02-03 20:21 UTC, FloppyDisck approved these changes

2022-02-03 20:24 UTC, merged