Oracle sienna
securesecrets/shade pull request #193
Opened 2022-03-11 18:10 UTC by DrPresident

Sienna integration with oracle, all registered pairs for a given symbol will be queried for their current return on a 1SCRT trade, as well as their pool depths. The return amounts will be averaged together weighted by their respective pool CP's. That value is then translated to a USD price based on the SCRT/USD value provided by BAND.

2022-03-18 19:01 UTC, FloppyDisck requested changes

2022-03-18 19:03 UTC, FloppyDisck commented
I recommend looking into https://github.com/hackbg/fadroma/tree/v100/crates/fadroma-ensemble
Its made by the Sienna devs and it offers cross contract unit testing, im planning on using it for governance and it would be super useful if you used it for the oracle to prove that it all works in a quick manner (way faster than the our python/rust integration tests)

2022-03-21 19:33 UTC, DrPresident commented on contracts/oracle/src/state.rs
I'm not gonna update all the oracle code as its probably going to get removed in favor of the `shade-oracle`

2022-03-22 15:24 UTC, FloppyDisck commented on contracts/oracle/src/state.rs
noted

2022-03-24 16:56 UTC, wahlbergkyle approved these changes

2022-03-29 15:33 UTC, merged