Treasury adapters
securesecrets/shade pull request #204
Opened 2022-05-02 21:44 UTC by DrPresident

Major Changes: 
`treasury`
- Only does allowances for outgoing
- Basic Rebalancing (needs refining)
- Unbonding from adapters
- Rough start for whitelisted unbonding from treasury

`adapter`
- Basic interface for per-asset treasury integration (subject to changes)
- unbonding - pulling assets from an adapter
- balance - checking balance on a given asset
- claiming - collecting funds that have been unbonded
- updating - regular maintenance handle

`treasury_manager`
- Allocates funds among adapters from treasury allowance
- Rebalancing (needs refining)

`rewards_emission`
- Holding treasury allowance for collection for a given `target` to refill its rewards
- NOTE - very rough, will refine once swap is ready for integration

`scrt_staking`
- Reworked for adapter interface
- TODO: voting from govt (Authz)?

2022-05-04 18:13 UTC, FloppyDisck requested changes

2022-05-04 18:13 UTC, FloppyDisck commented on packages/shade_protocol/Cargo.toml
> +chrono = "0.4.19"
needs optional flag

2022-05-04 18:13 UTC, FloppyDisck commented on packages/shade_protocol/Cargo.toml
> +secret-cosmwasm-math-compat = { git = "https://github.com/chris-ricketts/secret-cosmwasm-math-compat.git", branch = "main" }
we're using the math-compat library in the packages folder

2022-05-04 18:13 UTC, FloppyDisck commented on packages/shade_protocol/src/dex.rs
> +    cosmwasm_std::Uint128(take_pool.u128() - give_pool.u128() * take_pool.u128() / (give_pool + give_amount).u128())
Its better to use `cosmwasm_math_compat`'s checked math functions for added safety
```suggestion
take_pool.checked_sub(give_pool.checked_mul(take_pool)?.checked_div(give_pool.checked_add(give_amount)?)?)?.into()
```

2022-05-04 18:13 UTC, FloppyDisck commented on packages/shade_protocol/src/treasury.rs
>      pub viewing_key: String,
wouldn't it be better to provide a seed and allow treasury to generate its own viewing key? Setting the key removes any privacy the contract might have since we can see its whole snip20 transfer history

2022-05-04 18:13 UTC, FloppyDisck commented on packages/shade_protocol/src/utils/mod.rs
> +pub mod wrap;
should be in their own features

2022-05-04 18:41 UTC, DrPresident commented on packages/shade_protocol/src/treasury.rs
>      pub viewing_key: String,
We don't want privacy on the treasury, we can make the viewing key as complex as we want when we deploy but we want to know it for ourselves, as well as treasury transactions can be public

2022-05-04 18:41 UTC, DrPresident commented on packages/shade_protocol/src/utils/mod.rs
> +pub mod wrap;
IMO having a feature for every single file is overkill. it makes importing things a pain you have to add it in like 3 different places if you want to use it

2022-05-04 18:42 UTC, DrPresident commented on contracts/rewards_emission/src/state.rs
> +}
I'll add in the future things as the support develops

2022-05-04 18:50 UTC, FloppyDisck commented on contracts/rewards_emission/src/state.rs
> +}
Sounds good

2022-05-04 18:53 UTC, FloppyDisck commented on packages/shade_protocol/src/utils/mod.rs
> +pub mod wrap;
You only need to add it where youre using it (either the contract or the contract interfaces feature)
Because of the latest max gas reductions; we want to keep compiled code as small as possible, this includes keeping most packages in features so we dont compile each contract with unused code

2022-05-09 16:46 UTC, FloppyDisck requested changes

2022-05-09 16:46 UTC, FloppyDisck commented on contracts/oracle/Cargo.toml
> +fadroma = { version = "22.1.0", git = "https://github.com/hackbg/fadroma.git" }
You can also import specific packages if theyre in the same cargo workspace, such as
`fadroma-ensemble = { branch = "v100", git = "https://github.com/hackbg/fadroma.git" }`

2022-05-09 16:46 UTC, FloppyDisck commented on contracts/oracle/Cargo.toml
> +fadroma = { version = "22.1.0", git = "https://github.com/hackbg/fadroma.git" }
The branch v100 is the latest version and the first full version, the deps should point to that one to reduce any possible testing errors caused by previous versions

2022-05-09 16:46 UTC, FloppyDisck commented on contracts/oracle/src/query.rs
> +        Uint128::try_from(price * Uint512::from(10u128.pow(18)) / weight_sum)?.u128(),
```suggestion
        Uint128::try_from(price.checked_mul(Uint512::from(10u128.pow(18)))?.checked_div(weight_sum)?)?.u128(),
```

2022-05-09 22:21 UTC, FloppyDisck approved these changes

2022-05-10 18:18 UTC, merged