Shade bonds
securesecrets/shade pull request #205
Opened 2022-05-06 17:30 UTC by wahlbergkyle

# Description

## Notable changes

- Lowered gas price on contract handle
- Added new contract query

## Next steps

- Documentation should be updated for query
- More tests to calculate gas price

2022-05-17 22:05 UTC, DrPresident commented on contracts/bonds/src/contract.rs
> +        admin: msg.admin,
Not critical right now but I've been trying to move to an `admins: vec![]` so we can have multiples, e.g. govt & multisig

2022-05-17 22:05 UTC, DrPresident commented on contracts/bonds/src/contract.rs
> +    collateral_assets_w(&mut deps.storage).save(&assets)?;
This can be 1 line

2022-05-17 22:05 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +
Theres alot of these double & triple newlines, try to trim these out

2022-05-17 22:05 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +    let (amount_to_issue, deposit_price, claim_price, discount_price) = amount_to_issue(&deps, deposit_amount, available, bond_opportunity.deposit_denom.clone(), issuance_asset, bond_opportunity.disc
This line is really long

2022-05-17 22:05 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +    // Add case for if total is 0, error out
If this is coming later lead the line with `TODO`

2022-05-18 16:53 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +    let (amount_to_issue, deposit_price, claim_price, discount_price) = amount_to_issue(&deps, deposit_amount, available, bond_opportunity.deposit_denom.clone(), issuance_asset, bond_opportunity.disc
Are you suggesting to change the function/return setup or just add newlines to make it more readable?

2022-05-18 17:11 UTC, wahlbergkyle commented on contracts/bonds/src/contract.rs
> +    collateral_assets_w(&mut deps.storage).save(&assets)?;
I'd had it on 2 lines in case the HumanAddr type would be lost by just placing `vec![]`, but it looks like it's fine without the declaration

2022-05-19 18:00 UTC, FloppyDisck requested changes

2022-05-19 21:01 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +            if None == collateral_assets_r(&deps.storage).may_load()?{
I would either do `if let Some(x) = ...` or do a`match x { Some => {} None => {} }`

2022-05-19 21:01 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +        &deps.querier,
indentation

2022-05-19 21:01 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +            Ok(c) => Option::from(c),
I believe this is all handled by the `shade_protocol::snip20::fetch_snip20` in almost the exact same way

2022-05-20 20:38 UTC, FloppyDisck commented on contracts/bonds/src/handle.rs
> +    )?);
to add to this, you can automatically fix most of the indentation issues by running `cargo fmt`

2022-05-23 05:07 UTC, wahlbergkyle commented on contracts/bonds/Cargo.toml
> +mockall_double = "0.2.0"
Can do, but what about these requires a different category?

2022-05-23 05:09 UTC, wahlbergkyle commented on packages/secretcli/src/secretcli.rs
> +pub fn start_loaded_local_testnet() -> Result<TxResponse> {
I removed all these docker-related lines, these were relics from before I learned about the container you'd created and was trying to create something myself.

2022-05-23 05:19 UTC, wahlbergkyle commented on contracts/bonds/README.md
> +Contract responsible to handle snip20 airdrop
Aha whoops

2022-05-23 05:21 UTC, wahlbergkyle commented on contracts/bonds/src/contract.rs
> +    global_total_issued_w(&mut deps.storage).save(&Uint128(0))?;
Sure, I'll look for others and do the same.

2022-05-23 05:23 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +        if(reset_total_issued) {
Old habits die hard sometimes haha. Fixed

2022-05-23 05:24 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +        return Err(blacklisted(config.treasury));
Thanks! Copied your structure from Airdrop, and it has made Austin's life much easier, so it's a gift that keeps giving.

2022-05-23 05:25 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +            account
Much cleaner, thanks.

2022-05-23 05:29 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +    for bond in pending_bonds_iter{
I'll have less of these unnecessary declarations in the future, some of these were a product of learning and trying on the fly. Sort of reminds me of high school CS exams where they'd ask for all the declarations as proof of work haha

2022-05-23 05:34 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +    )?);
`cargo fmt` is very helpful, thanks. Fixed the indentation errors.

2022-05-23 05:35 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +    )?);
No, I was intending to send/transfer, but I'm guessing they aren't the same thing based off you asking haha. I switched it to `send`, what's the difference?

2022-05-23 05:39 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +
`cargo fmt` took care of these, so fixed accidentally

2022-05-23 05:42 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +            Ok(c) => Option::from(c),
Yes it does, and that's one line versus a dozen+! I'll change the couple instances of this to `fetch_snip20` instead.

2022-05-23 05:51 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +            if None == collateral_assets_r(&deps.storage).may_load()?{
Is there a difference in security or functionality compared to the current implementation?

2022-05-23 19:27 UTC, DrPresident commented on contracts/bonds/Cargo.toml
> +mockall_double = "0.2.0"
they are for testing only, you probably aren't actually using them in your contract and they can likely be removed

2022-05-23 19:28 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +    )?);
I don't really know what the difference is actually, I figured you had chosen transfer for a reason. If I had to guess it would be a difference in how the `receive` callback is handled (likely its skipped for a "transfer")

2022-05-23 19:29 UTC, DrPresident commented on contracts/bonds/src/handle.rs
> +            if None == collateral_assets_r(&deps.storage).may_load()?{
Its just the rust way to do things, it shouldn't affect anything but doing things the more idiomatic way is preferred

2022-05-23 19:32 UTC, FloppyDisck commented on contracts/bonds/src/handle.rs
> +    )?);
correct send calls the callback if present. Send is better since we indirectly give support to any smart contract interacting with this

2022-05-24 16:39 UTC, wahlbergkyle commented on contracts/bonds/src/handle.rs
> +    )?);
Good to know, thanks.

2022-05-24 22:05 UTC, wahlbergkyle commented on contracts/bonds/src/contract.rs
> +        admin: msg.admin,
Just implemented, along with AddAdmin and RemoveAdmin functions the limit admin can take

2022-05-25 22:02 UTC, FloppyDisck requested changes

2022-05-25 22:02 UTC, FloppyDisck commented on contracts/bonds/src/handle.rs
> +}
missing checked math

2022-05-25 22:46 UTC, FloppyDisck approved these changes

2022-05-25 22:46 UTC, FloppyDisck commented on contracts/bonds/src/handle.rs
> +            prevUint128(amount_to_issue.u128()),
Still missing some Uint128 fixed here

2022-05-27 19:01 UTC, merged