reorganize shade protocol package
securesecrets/shade pull request #210
Opened 2022-05-11 19:18 UTC by FloppyDisck

# Description
Reorganized the smart contract interfaces in `shade_protocol` to be inside their own categorized folders

## Next steps

- Improve naming such as `staking::snip20_staking` to `staking::snip20`

2022-05-11 19:33 UTC, wahlbergkyle approved these changes

2022-05-11 20:23 UTC, DrPresident approved these changes

2022-05-11 20:26 UTC, DrPresident requested changes
We should move `treasury/treasury_manager/scrt_staking` into `dao`, potentially also `adapter` & `rewards_emissions/lp_shade_swap` (can't remember if etiher of those had been merged yet)

2022-05-12 17:50 UTC, DrPresident approved these changes

2022-05-13 17:52 UTC, merged