Sky feature
securesecrets/shade pull request #234
Opened 2022-07-12 16:38 UTC by SissonJ

# Description

General implementation of sky arbitrage contract

## Notable changes

- Further built out handle and queries
- Added cycles with a validation method
- Implemented generalized methods for the ArbPair struct
- Moved away from specialized msg for Conversion minting

## Next steps

- integration tests
- Documentation

2022-07-12 18:42 UTC, FloppyDisck requested changes

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/contract.rs
> +        sscrt_token_contract: msg.sscrt_token_contract.clone(),
Can these be generalized to generic snip20's?

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/contract.rs
> +        )?,
Should this also be registering receive?

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +    }
```suggestion
    let silk_bal = match res {
        snip20::QueryAnswer::Balance { amount } => amount,
        _ => { // error here }
    }
```

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +    }
Same here

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +        cycles: Cycles::load(&deps.storage)?.0,
Not sure how many cycles we plan to have but this may need some pagination of some kind

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +            backtrace: None,
```suggestion
        return Err(StdError::generic_err ("More swap amounts than arb pairs"));
```

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +        profit: Uint128::zero(),
is_profitable could possibly be removed entirely for just the `profit` parameter, letting the client choose acceptable margins

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/src/query.rs
> +    }
This should be optimized to only query the balance of the requested token, otherwise you make 2 unused balance queries

2022-07-12 20:12 UTC, DrPresident commented on contracts/sky/tests/integration.rs
> +    ensemble
Could some of this be left uncommented? I'd rather have _some_ testing even if its just deployment & configuration with some basic queries

2022-07-12 21:09 UTC, scrtreddev commented on contracts/sky/src/handle.rs
> +    // Admin-only
could probably make a separate helper function for this

2022-07-13 15:02 UTC, SissonJ commented on contracts/sky/Cargo.toml
>  snip20-reference-impl = { version = "0.1.0", path = "../../contracts/snip20-reference-impl" }
removed

2022-07-13 15:03 UTC, SissonJ commented on packages/shade_protocol/src/contract_interfaces/sky/mod.rs
> +pub struct ArbPair {
I think I did this but maybe not

2022-07-13 15:04 UTC, SissonJ commented on contracts/sky/src/contract.rs
> +        )?,
Sky doesn't execute with the receiver callback so there's no need to register receive

2022-07-13 15:04 UTC, SissonJ commented on contracts/sky/src/contract.rs
> +        sscrt_token_contract: msg.sscrt_token_contract.clone(),
as in registering assets?

2022-07-13 16:14 UTC, SissonJ commented on contracts/sky/src/query.rs
> +    }
done

2022-07-13 16:18 UTC, SissonJ commented on contracts/sky/src/query.rs
> +        cycles: Cycles::load(&deps.storage)?.0,
I can't imagine we'll ever have 30 cycles, if we do, we can add it to v2

2022-07-13 16:49 UTC, FloppyDisck requested changes

2022-07-13 16:49 UTC, FloppyDisck commented on contracts/sky/Cargo.toml
> +sky = { version = "0.1.0", path = "../../contracts/sky" }
cyclical import

2022-07-13 16:49 UTC, FloppyDisck commented on contracts/sky/src/handle.rs
> +                payback_amount = profit * payback_percent;
use checked math

2022-07-13 16:49 UTC, FloppyDisck commented on contracts/sky/src/handle.rs
> +                            index: Uint128::from(i as u16),
```suggestion
                            index: Uint128::from(i as u128),
```

using as u16 makes the struct later convert into u128

2022-07-13 16:49 UTC, FloppyDisck commented on contracts/sky/src/query.rs
> +        cycles: Cycles::load(&deps.storage)?.0,
check it never goes above 40 or so, arrays are no efficient for large data storage

2022-07-13 16:49 UTC, FloppyDisck commented on contracts/sky/src/query.rs
> +    if (index.u128() as usize) >= cycles.len() {
ovewrite the index so you dont have to convert to usize each time

2022-07-13 16:49 UTC, FloppyDisck commented on packages/shade_protocol/Cargo.toml
> +dex = ["utils", "math", "snip20", "mint", "band", "dep:fadroma"]
theyre still importing fadroma

2022-07-13 16:49 UTC, FloppyDisck commented on packages/shade_protocol/src/contract_interfaces/sky/cycles.rs
> +    ) -> Result<CosmosMsg, StdError> {
```suggestion
    ) -> StdResult<CosmosMsg> {
```
```suggestion
    ) -> Result<CosmosMsg, StdError> {
```

2022-07-13 17:05 UTC, SissonJ commented on contracts/sky/src/handle.rs
> +                payback_amount = profit * payback_percent;
checked math not available when multiplying a Uint128 by a Decimal

2022-07-13 17:05 UTC, SissonJ commented on contracts/sky/Cargo.toml
> +sky = { version = "0.1.0", path = "../../contracts/sky" }
Done

2022-07-13 17:06 UTC, SissonJ commented on contracts/sky/src/handle.rs
> +                            index: Uint128::from(i as u16),
Done

2022-07-13 18:42 UTC, FloppyDisck commented on contracts/sky/src/handle.rs
> +                payback_amount = profit * payback_percent;
leave a TODO for cosmwasm v1

2022-07-13 18:43 UTC, FloppyDisck approved these changes

2022-07-13 21:37 UTC, merged