Dao upgrade
securesecrets/shade pull request #276
Opened 2022-08-31 04:53 UTC by DrPresident

DAO working with V1 feature set, will likely add more tests before launch but audit can likely begin
- Rebalance working with significant test cases
- Wrapping L1 tokens
- Shade Admin
- Batch Balances

2022-08-31 15:08 UTC, SissonJ requested changes

2022-08-31 15:08 UTC, SissonJ commented on rust-toolchain
> +nightly
I think you added alot of files that you didn't mean to

2022-08-31 15:08 UTC, SissonJ commented on test-scripts/arbitrage.py
> +import secrets
You pushed it again

2022-09-15 20:01 UTC, FloppyDisck commented on contracts/dao/treasury/src/contract.rs
>      SELF_ADDRESS.save(deps.storage, &env.contract.address)?;
same as the others

2022-09-15 20:15 UTC, FloppyDisck commented on contracts/dao/treasury/src/query.rs
> +    epoch: Option<Uint128>,
Can be replaced for u64

2022-09-15 20:17 UTC, FloppyDisck commented on contracts/dao/treasury/tests/dao/equilibrium.rs
> +            8
No need to specify the size in these cases

2022-09-15 20:21 UTC, FloppyDisck commented on contracts/dao/treasury/Cargo.toml
>    "treasury",
can be removed

2022-09-15 20:21 UTC, FloppyDisck commented on contracts/dao/treasury/Cargo.toml
> +  "snip20",
can be removed

2022-09-15 20:21 UTC, FloppyDisck commented on contracts/dao/treasury/Cargo.toml
> +  "dao",
can be removed

2022-09-15 20:22 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/contract.rs
>      SELF_ADDRESS.save(deps.storage, &env.contract.address)?;
can be removed

2022-09-15 20:26 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
> +    validate_admin(
admin validation could be moved outside of the functions, see governance's solution as an example

2022-09-15 20:27 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
>      match stale_alloc {
replace with `if let Some(i) = stale_alloc`

2022-09-15 20:29 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
> +    let send_amount = {
could be replaced by the match style you used in line 288

2022-09-15 20:34 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
> +            // TODO figure out why we can't throw an error here
It might have to do with the fact that the return is in the scope of assigning `unbond_amount` instead of the function itself

2022-09-15 20:34 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
>          reserves = reserves - other_unbondings;
replace with `-=`

2022-09-15 20:36 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
> +                holding.unbondings[i].amount = holding.unbondings[i].amount - reserves;
`-=`

2022-09-15 20:36 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/execute.rs
> +                holding.unbondings[i].amount = holding.unbondings[i].amount - amount;
same here

2022-09-15 20:37 UTC, FloppyDisck commented on contracts/dao/treasury_manager/src/query.rs
> +    epoch: Option<Uint128>,
change to `Option<u64>`

2022-09-15 20:38 UTC, FloppyDisck commented on contracts/dao/treasury_manager/Cargo.toml
> +  "snip20",
remove

2022-09-15 20:38 UTC, FloppyDisck commented on contracts/dao/treasury_manager/Cargo.toml
>    "treasury_manager",
remove

2022-09-15 20:38 UTC, FloppyDisck commented on contracts/dao/treasury_manager/Cargo.toml
> +  "dao",
remove

2022-09-15 20:40 UTC, FloppyDisck commented on contracts/sky/src/contract.rs
>          ExecuteMsg::Adapter(adapter) => match adapter {
`asset` can be moved outisde the adapter enum

2022-09-15 20:40 UTC, FloppyDisck commented on contracts/sky/src/contract.rs
>          QueryMsg::Adapter(adapter) => match adapter {
same here

2022-09-15 20:42 UTC, FloppyDisck commented on contracts/snip20/src/batch.rs
> +//! Types used in batch operations
move file into the interface

2022-09-15 20:44 UTC, FloppyDisck commented on packages/multi_test/src/interfaces/dao.rs
> +
import all these functions on `interfaces`  inside the `multi.rs` on their respective Contracts, that way importing them feels cleaner

2022-09-15 20:45 UTC, FloppyDisck commented on packages/multi_test/src/lib.rs
> +pub mod interfaces;
keep this private so the imports only come from `multi.rs`

2022-09-15 20:49 UTC, FloppyDisck commented on packages/shade_protocol/src/utils/storage/plus/iter_item.rs
>  mod tests {
`data` doesnt have to be mutable

2023-04-17 22:39 UTC, merged