Upgrade mock contracts, mock stkd
securesecrets/shade pull request #335
Opened 2023-02-16 16:51 UTC by a-stgeorge

# Description

Useful update for testing in cw v1 with anything that would need dex transactions or uses the stkd derivative (particularly useful for stkd arbitrage testing).

## Notable changes

- Upgrades the mock sienna pair contract to cw v1 and add swap execute message.
- Adds a mock stkd contract that simulates staking, unbonding, and claiming.

2023-02-21 16:00 UTC, SissonJ commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                    match pair_info.pair.token_0.clone() {
If we have it doing actual swaps, wouldn't it make sense to use it's balance? Not using balance is fine, but then you have to make sure not to execute a swap that would return an amount greater than the balance

2023-02-21 16:02 UTC, SissonJ commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                                    amount_1: pair_info.amount_1 + return_amount,
subtract the return amount no?

2023-02-21 16:04 UTC, SissonJ commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                    match pair_info.pair.token_1.clone() {
Same in  this section for balance

2023-02-21 16:05 UTC, SissonJ commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +        PairQuery::PairInfo => {
This about using balances here

2023-02-21 16:21 UTC, SissonJ commented on packages/shade_protocol/src/contract_interfaces/mock/mod.rs
> +use crate::{
As we talked about, Keep these schemas in the contract.rs since these contracts are not meant to be used anywhere but multi test

2023-02-22 21:50 UTC, a-stgeorge commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                    match pair_info.pair.token_0.clone() {
Switched contract to use balance now

2023-02-22 21:50 UTC, a-stgeorge commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                                    amount_1: pair_info.amount_1 + return_amount,
Good catch!

2023-02-22 21:51 UTC, a-stgeorge commented on packages/shade_protocol/src/contract_interfaces/mock/mod.rs
> +use crate::{
Makes sense, moved schema

2023-03-06 21:16 UTC, SissonJ approved these changes

2023-03-07 22:09 UTC, GumboLimbo requested changes

2023-03-07 22:09 UTC, GumboLimbo commented on contracts/mock/mock_stkd_derivative/src/contract.rs
> +                unbonding_time: 2u32,
Is it possible to un-hardcode this?

2023-03-20 20:51 UTC, a-stgeorge commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                        if return_amount > expected_return.unwrap_or(Uint128::MAX) {
Good catch

2023-03-20 20:51 UTC, a-stgeorge commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                                    return_amount - commission,
Nope! good catch

2023-03-20 20:55 UTC, a-stgeorge commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                    let commission = amount.multiply_ratio(Uint128::new(3), Uint128::new(1000));
yep!

2023-03-20 21:15 UTC, GumboLimbo commented on contracts/mock/mock_sienna_pair/src/contract.rs
> +                    liquidity_token: Contract::new(&Addr::unchecked("lp_token"), &"hash".to_string()),
Yes you're right, factory should always be the same, and if lp token isn't used I agree this won't cause any problems

2023-03-21 19:58 UTC, GumboLimbo approved these changes

2023-04-20 17:26 UTC, merged