Burn and mint
securesecrets/shade pull request #336
Opened 2023-03-14 19:57 UTC by SissonJ

Contract to facilitate the migration of Snip20s to the Snip25 standard

2023-03-15 20:28 UTC, DrPresident requested changes

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/src/contract.rs
> +        QueryMsg::RegistragionStatus { token } => to_binary(&QueryAnswer::RegistrationStatus {
typo

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/src/contract.rs
> +            },
Should error for invalid tokens, and return 0 for valid tokens with nothing minted not null

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/src/contract.rs
> +    )?))
Tokens are never burned

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/tests/mod.rs
This isn't a package, the name should be informational not `mod.rs` as that implies it contains package exports

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/tests/mod.rs
> +            }
these asserts will fail and give no information on the failure. it should be `assert_eq!(config. expected_config, "helpful error info")`

2023-03-15 20:28 UTC, DrPresident commented on contracts/snip20_migration/tests/mod.rs
> +        _ => assert!(false),
also an unhelpful failure, should be `panic!("helpful information")`

2023-03-15 20:28 UTC, DrPresident commented on packages/shade_protocol/src/contract_interfaces/snip20_migration/mod.rs
> +    const MAP: Map<'static, String, Self> = Map::new("registered_tokens-");
Storage stuff doesn't belong in this file

2023-03-15 21:59 UTC, FloppyDisck requested changes

2023-03-15 21:59 UTC, FloppyDisck commented on contracts/snip20_migration/src/contract.rs
> +        QueryMsg::Metrics { token } => to_binary(&QueryAnswer::Metrics {
Note that this exposes the possibility of knowing user migrated balances

2023-03-15 21:59 UTC, FloppyDisck commented on contracts/snip20_migration/src/contract.rs
> +            },
Agree, replace option with a result

2023-03-15 21:59 UTC, FloppyDisck commented on contracts/snip20_migration/tests/mod.rs
Agree, maybe this could be better off inside `src`

A separate test folder works when you have multiple files that share some helper functions

2023-03-15 21:59 UTC, FloppyDisck commented on contracts/snip20_migration/tests/mod.rs
> +        },
```suggestion
        snip20_migration::QueryAnswer::Metrics { amount_minted } => assert!(amount_minted.is_none()),
```

2023-03-15 21:59 UTC, FloppyDisck commented on contracts/snip20_migration/tests/mod.rs
> +        },
many of the matches can be unwrapped into smaller things like these

2023-03-15 21:59 UTC, FloppyDisck commented on packages/shade_protocol/src/contract_interfaces/snip20_migration/mod.rs
> +    const MAP: Map<'static, String, Self> = Map::new("registered_tokens-");
agree

2023-03-23 15:55 UTC, SissonJ commented on contracts/snip20_migration/src/contract.rs
> +    )?))
Tokens are burned by being received by the contract and having no way to leave, we can't guarantee that every snip20 we might want to use this contract for will have burn enabled

2023-03-23 17:23 UTC, FloppyDisck commented on contracts/snip20_migration/src/contract.rs
> +    )?))
You could have a flag for it, or idk if the snip20 config shows that info but you could also query the config and store whether the snip has burn enabled or not

2023-03-24 19:02 UTC, DrPresident commented on contracts/snip20_migration/src/contract.rs
> +    )?))
The only use-case currently for this contract is SHD, which can be burned. IMO we should actually burn those tokens so the total supply reflects the transition to the new token. The best solution here is what guy suggested and query the token config when it is registered and burn if able.

2023-03-27 18:27 UTC, DrPresident approved these changes

2023-03-27 19:35 UTC, merged