Added Libraries
securesecrets/shade pull request #358
Opened 2023-08-11 07:48 UTC by itsHaseebSaeed

Libraries needed for liquidity book are added

2023-08-11 18:27 UTC, kent-3 requested changes
Thanks for starting on this! For the first PR,  I think we should be extra careful not to mess up the existing cargo workspace and packages. Please see my other comments for my ideas on that.

2023-08-11 18:27 UTC, kent-3 commented on contracts/liquidity_book/Cargo.toml
> +    "libraries",
This Cargo.toml file is defining a [virtual workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace). The members should also include the LB contracts.

2023-08-11 18:27 UTC, kent-3 commented on contracts/liquidity_book/Cargo.toml
> +[dependencies]
This table should be `[workspace.dependencies]` which will make them usable by all members of the workspace. [(more info)](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table)

This ensures all members will inherit the same versions of the dependencies. Here is an [example](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) for how to do that.

2023-08-11 18:27 UTC, kent-3 commented on contracts/liquidity_book/Cargo.toml
> +[dev-dependencies]
In `[workspace.dependencies]` there is no separate table for dev-dependencies. You would lump them together here, then import them as dev-dependencies in the individual packages.

2023-08-11 18:27 UTC, kent-3 commented on contracts/liquidity_book/Cargo.toml
> +[lib]
I don't think you can use `[lib]` or `[features]` in a virtual workspace. These go in each package's manifest.

2023-08-11 18:27 UTC, kent-3 commented on packages/shade_protocol/Cargo.toml
> +ethnum = { version = "1" }
I'm not sure we should mess with the `shade_protocol` package. My thought is to have a separate folder like `/shade/packages/liquidity_orderbook/` for these libraries.

2023-08-11 18:27 UTC, kent-3 commented on packages/shade_protocol/src/utils/mod.rs
> +pub mod liquidity_book;
This feels wrong to me :skull:. I think we shouldn't mix with the core `shade_protocol` package.

2023-08-11 20:19 UTC, itsHaseebSaeed commented on contracts/liquidity_book/Cargo.toml
> +    "libraries",
My bad I forgot to remove this

2023-08-11 20:35 UTC, kent-3 commented on contracts/liquidity_book/Cargo.toml
> +    "libraries",
But I think we should keep it. Let's see how having a nested workspace goes.

2023-08-11 20:36 UTC, itsHaseebSaeed commented on contracts/liquidity_book/Cargo.toml
> +    "libraries",
Nested workspaces don't work according to my knowledge

2023-08-11 20:37 UTC, itsHaseebSaeed commented on packages/shade_protocol/src/utils/mod.rs
> +pub mod liquidity_book;
Gottca

2023-08-11 20:41 UTC, itsHaseebSaeed commented on contracts/liquidity_book/Cargo.toml
> +[lib]
I totally forgot to remove that 💀

2023-08-11 20:42 UTC, itsHaseebSaeed commented on contracts/liquidity_book/Cargo.toml
> +[dependencies]
Same as above.

2023-08-14 13:29 UTC, itsHaseebSaeed commented on contracts/liquidity_book/Cargo.toml
> +    "libraries",
removed this cargo.toml file for now.

2023-08-14 13:29 UTC, itsHaseebSaeed commented on packages/shade_protocol/Cargo.toml
> +ethnum = { version = "1" }
removed this cargo.toml file for now.

2023-08-14 13:31 UTC, itsHaseebSaeed commented
Created a separate package foe liquidity book

2023-08-14 14:26 UTC, AustinWoetzel commented on packages/shade_protocol/Cargo.toml
> +
lets remove this added line so as to not confuse the commit history on the main cargo.toml

2023-08-14 14:30 UTC, itsHaseebSaeed commented on packages/shade_protocol/Cargo.toml
> +
Fixed

2023-08-14 18:36 UTC, AustinWoetzel commented
are these going to be used by multiple contracts? I think you guys mentioned that liquidity book contained 5 different contracts. I would expect each of these contracts to get their own sub directory, then any helper functions like this would be imported from another directory elsewhere? @DrPresident what are your thoughts here?

![image](https://github.com/securesecrets/shade/assets/30289932/4443f736-b68b-40be-a913-6e0a79b475e3)

2023-08-15 18:26 UTC, merged